### ISSUE TITLE
App crashes on Android 6.0

### ISSUE THREAD

**Issue by Gelassen** [hyperledger/iroha-android#74]
### The issue
Can not run android application on Android 6.0 (crash in runtime), but it works correctly on Android 5.0

### Environment
Android Nexus, Android 6.0

### Steps to reproduce
1. Clone the repo
2. Run the application on Android 6.0

### Observed result
App mingles with screen and Android return back to launcher window 

### Expected result
App shows registration screen

Stacketrace from unit test: 
```

java.io.IOException: Error while finalizing cipher
at javax.crypto.CipherInputStream.fillBuffer(CipherInputStream.java:104)
at javax.crypto.CipherInputStream.read(CipherInputStream.java:130)
at io.soramitsu.irohaandroid.security.KeyStoreManager.decrypt(KeyStoreManager.java:172)
at io.soramitsu.iroha.CipherTest.testDecryptionOnEmptyString(CipherTest.java:21)
at android.test.InstrumentationTestCase.runMethod(InstrumentationTestCase.java:214)
at android.test.InstrumentationTestCase.runTest(InstrumentationTestCase.java:199)
at android.test.AndroidTestRunner.runTest(AndroidTestRunner.java:191)
at android.test.AndroidTestRunner.runTest(AndroidTestRunner.java:176)
at android.test.InstrumentationTestRunner.onStart(InstrumentationTestRunner.java:555)
at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1879)
Caused by: javax.crypto.IllegalBlockSizeException
at android.security.keystore.AndroidKeyStoreCipherSpiBase.engineDoFinal(AndroidKeyStoreCipherSpiBase.java:486)
at android.security.keystore.AndroidKeyStoreCipherSpiBase.engineDoFinal(AndroidKeyStoreCipherSpiBase.java:498)
at javax.crypto.Cipher.doFinal(Cipher.java:1476)
at javax.crypto.CipherInputStream.fillBuffer(CipherInputStream.java:102)
... 15 more
Caused by: android.security.KeyStoreException: Unknown error
at android.security.KeyStore.getKeyStoreException(KeyStore.java:632)
at android.security.keystore.KeyStoreCryptoOperationChunkedStreamer.doFinal(KeyStoreCryptoOperationChunkedStreamer.java:224)
at android.security.keystore.AndroidKeyStoreCipherSpiBase.engineDoFinal(AndroidKeyStoreCipherSpiBase.java:473)
... 18 more
```

**Comment by kobaken0029** [comment]
This issue was already resolve for me. but not merge to master yet. now, 'develop' branch is usable!
I will merge to master from develop as soon as possible. please just a moment.

**Comment by Gelassen** [comment]
Checked on my side. App starts without crash! Thank you for fix. 

Could you please give more details what was the root cause?

**Comment by kobaken0029** [comment]
I guess I was not prepare keypair for encripting/decripting. but I forced decript on sample app. Maybe, this is my mistaken the usase. Sorry^^;

**Comment by Gelassen** [comment]
Excuse me, but I don't get your explanation :( May I ask you to schedule a call to discuss this? It would be good also to go through others questions I have (you may found skype id in email I shared yesterday)

**Comment by kobaken0029** [comment]
Opps… I'm sorry because I'm not good at my English.
OK, I'm trying to prepare a time. But I'm busy on today. So I will contact you again tomorrow!

**Comment by Gelassen** [comment]
Great! Looking forward to speak with you soon

Kind regards,
Dmitry Kazakov

2017-03-03 15:37 GMT+08:00 Kento Kobayashi <notifications@github.com>:

**Comment by Gelassen** [comment]
Hello Kobaken, do you have a chance to have a call or chat via skype today?
